feat: provision ownership on /var/lib/deadline/credentials directory
aws-deadline/deadline-cloud-worker-agent pull request #145
Opened 2024-02-02 18:55 UTC by gahyusuh

### What was the problem/requirement? (What/Why)
The worker credentials directory `/var/lib/deadline/credentials` is world read/executable in a worker agent in a SMF. While the credentials for the worker agent are not accessible, we should make this directory inaccessible as a best practice.

### What was the solution? (How)
Updated the `install.sh` to pre-create the directory and set the correct ownership and permissions. This ensures that the directory is secure from the moment it's created, aligning with best practices for handling sensitive directory.

### What is the impact of this change?
This change proactively secures the credentials directory.

### How was this change tested?
- `hatch run fmt && hatch run lint && hatch run test`
- E2E test by cleaning all the persistence directories and re-installing worker agent by running this command:
  ```
  hatch shell
  install-deadline-worker --farm-id $FARM_ID --fleet-id $FLEET_ID
  ```
  After the installation, I confirmed the ownership and permissions of the directories:
  ```
  (24-02-02 21:28:41) <0> [/var/lib]  
  dev-dsk-gahyusuh-2a-387e0b51 % sudo ls -ld deadline/
  drwxr-x--- 4 deadline-worker-agent deadline-job-users 4096 Feb  2 21:16 deadline/

  (24-02-02 21:29:25) <0> [/var/lib]  
  dev-dsk-gahyusuh-2a-387e0b51 % sudo ls -ld deadline/credentials
  drwx------ 2 deadline-worker-agent root 4096 Feb  2 21:16 deadline/credentials
  ```
  - `/var/lib/deadline`: The owner `deadline-worker-agent` has full access. The owning group `deadline-job-users` has read and execute permissions. No permissions have been granted to other users.
  - `/var/lib/deadline/credentials`: Only the owner `deadline-worker-agent` has full access. Neither the owning group members nor any other users have been granted any permissions.

### Was this change documented?
No.

### Is this a breaking change?
No.

2024-02-02 19:22 UTC, jusiskin requested changes
Thanks for helping improve this. Just one suggested change here.

2024-02-02 20:07 UTC, jusiskin requested changes

2024-02-02 22:18 UTC, jusiskin approved these changes

2024-02-05 17:09 UTC, marofke approved these changes

2024-02-05 18:21 UTC, merged