feat: Basic Windows support
aws-deadline/deadline-cloud-worker-agent pull request #35
Opened 2023-09-18 22:01 UTC by gmchale79

### What was the problem/requirement? (What/Why)

The DLC worker agent did not start on Windows, and numerous unit tests did not pass. 

### What was the solution? (How)

Numerous small changes related to removing `NotImplemented` exceptions, using more appropriate file paths etc. 

User impersonation is not intended to work in this branch at this time, and several of the changes relate to ensuring tests pass when impersonation is not used. 

**As of 11/6/23 this is targeted at a feature branch, not mainline.** 

### What is the impact of this change?
The worker agent starts, then receives and executes jobs on Windows. 

### How was this change tested?
Submitting jobs to gamma and ensuring they are picked up and executed by a Windows worker. 

### Was this change documented?
No currently. 

### Is this a breaking change?
It is not intended to be.

2023-09-19 15:01 UTC, jusiskin requested changes
Thank you for taking on the first pass of adding Windows support to the worker agent. This is a great first step towards an important feature. It seems like this is a partial implementation, which is fine.

~~The biggest blocker to shipping this code is setting expectations for those using it. Specifically, if we don't yet support isolation of OS users then that limitation and its associated risks need to be made clear~~

EDIT: Sorry, I missed that this was targeting the `feature_windows` branch. I presume that we will have OS user impersonation when we merge this feature branch into `mainline`. On that basis, we can disregard my concern above.

2023-09-19 15:18 UTC, ddneilson requested changes

2023-10-02 22:15 UTC, ddneilson approved these changes

2023-10-04 18:55 UTC, jusiskin requested changes

2023-10-12 16:56 UTC, ddneilson submitted a review, later dismissed

2023-10-12 17:50 UTC, mwiebe requested changes

2023-11-06 19:35 UTC, mwiebe approved these changes

2023-11-06 21:01 UTC, anandgo1 approved these changes

2023-11-08 20:12 UTC, jusiskin approved these changes
This looks good to me.

A few small remaining nit-picks but they are not critical for merging

2023-11-08 20:17 UTC, merged